### ISSUE TITLE
Email Confirmation during registration - Not working

### ISSUE THREAD

**Issue by app-generator** [app-generator/boilerplate-code-django-dashboard#19]
## Expected Behavior:

- 1#: `.env` variable `EMAIL_CONFIRMATION` loaded in settings = `False` (default value)
  - user is register without a confirmation email 
  - Test STATUS **OK**

- 2#: - `.env` variable `EMAIL_CONFIRMATION` loaded in settings = `True` 
  - User create his account
  - The success message is: "Account Created - Please confirm your email"
  - User is flagged as inactive in database and cannot authenticate
  - User access the link sent in the confirmation email
  - Once the user click, account becomes active
  - User is now able to SIGN IN

  ## Current behavior 

- `.env` variable `EMAIL_CONFIRMATION` loaded in settings = `True` 
- User register a new account
- Account is active
- No confirmation email sent

The `register_user` method is not provided any code to process this use case:

```python
def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'User created - please <a href="/login">login</a>.'
            success = True

            # return redirect("/login/")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "accounts/register.html", {"form": form, "msg": msg, "success": success})
```

**Comment by koladev32** [comment]
Very strange. 

I've just followed all the scenarios and steps to reproduce the error, but it's working well from my side. What value for `EMAIL_BACKEND` are you using?

By the way, the `save` method of the `SignUpForm` form actually handles the user creation and check for the `EMAIL_CONFIRMATION`.

```python
# apps/authentication/forms.py
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if not settings.EMAIL_CONFIRMATION:
            if commit:
                user.save()
            return user

        user.is_active = False

        if commit:
            user.save()

        # Sending email
        token = account_activation_token.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        subject = 'Activate your account'
        message = f"This is your activation link. " \
                  f"http://localhost:8002/activate/{uid}/{token}/"
        send_mail(subject, message, settings.EMAIL_HOST_USER, [user.email])
        return user
```

**Comment by app-generator** [comment]
I will double-check this.
Please freeze the investigation for now

**Comment by app-generator** [comment]
If possible, please suggest a test scenario for local development.  

FYI, the flask version uses `[Flask-Mailman](https://www.waynerv.com/flask-mailman/)`, and the message is pushed using almost zero configuration and [SMTP4Dev](https://github.com/rnwood/smtp4dev) tool for local validation.

Ty @koladev32

**Comment by app-generator** [comment]
Ty @koladev32!
Closing.
