### ISSUE TITLE
Data Tables Clarifications

### ISSUE THREAD

**Issue by app-generator** [app-generator/boilerplate-code-django-dashboard#26]
Hello @koladev32!
Please reply with the following information

### The new app 

What problem solves and how

### The new models 

- Home / `Data Model`
- Datatables / `Transaction Model`

### Sample data

- Please save sample data in the media folder
- How to load sample data via admin
- How to add data via the interface 

The goal of this tracker is to accommodate fast the audience with the new feature. 
Ty!

**Comment by koladev32** [comment]
## Impact in the code
### The new app

The app datatables helps show transactions data in a table using Django. 
This app allows you to : 
- load sample data using the admin section
- Edit and delete rows 
- Edit rows by double-clicking on it
- Paginate and search for data in the table

### The new models

#### Home / Data Model

The `Data` model in `apps/home/models.py` contains four fields : 
- type (Char - product or transaction)
- name (Char)
- value (Integer)
- ts (for timestamp)

#### Datatables / Transaction Model

The `Transaction` model is made of 7 fields. This helps track all transactions happening on the dashboard. 
- bill_for (Char)
- issue_date (Date)
- due_date (Date)
- total (Decimal)
- status (Chars)
- created_time (Date time)
- updated_time (Date time)

### Sample data

#### Save sample data in the media folder

First, step you need to have a CSV file you'll import in the admin section. You can find an example of this [here](https://github.com/app-generator/boilerplate-code-django-dashboard/tree/master/sample_data). 
The CSV file should contain the following fields.  `id`, `bill_for`, `issue_date`, `due_date`, `total`, `status`. 

#### How to load sample data via admin

Go to the admin section at this URL. (`admin/apps_datatables/transaction/import/`)

![Importing screen](https://cdn.hashnode.com/res/hashnode/image/upload/v1636806692800/pmJ41uxDk.png)
Import the CSV file, choose `.csv` as the format and then load the data.

#### How to add data via the interface

You can also manually add some transactions data. The URL for this will be `/admin/apps_datatables/transaction/add/`. 

![Adding transaction](https://cdn.hashnode.com/res/hashnode/image/upload/v1636806796962/udBl8BuB0.png)

**Comment by app-generator** [comment]
Hello @koladev32, 

Thank you for your efforts. Just tested the feature, please find below my remarks: 

- Works perfectly over the transaction model
- I've moved the sample data to the media folder (just to have fewer dirs on the root)
- Regarding the pagination feature
  - the feature should manage the information from `data` model
    - `type` field = `transaction` 
  - `transaction` model should be removed
 
Defining two models might confuse people. Later on charts & API we will use the same `data` table to showcase the information without an additional table. 

Sorry if my requirements was not so clear from the beginning.

**Comment by app-generator** [comment]
Great work, Ty @koladev32.
Closing!
