### ISSUE TITLE
Why Django 2.2

### ISSUE THREAD

**Issue by namicts** [app-generator/boilerplate-code-django-dashboard#5]
Could I ask why you still keep Django version 2.2 not 3.*?

**Comment by app-generator** [comment]
Hello @namicts, 

Is about serving a larger userbase. All our starters are fairly simple, and apps can be upgraded to Django 3.x just by changing one line in the `requiremements.txt`. 
Many devs already made this update without facing issues in production. 
Feel free to do the same and let us know if you have issues. We will assist.

**Comment by namicts** [comment]
Thank you for the explanation.
