### ISSUE TITLE
RTL Support?

### ISSUE THREAD

**Issue by nisanb** [app-generator/boilerplate-code-django-dashboard#6]
Hi,
Is there RTL support for this boilerplate ?

**Comment by app-generator** [comment]
Hello @nisanb, 

This UI is not provided by the UI vendor (Codedthemes) with RTL Support. You can choose one from this list:

- [Django Black Dashboard](https://appseed.us/admin-dashboards/django-dashboard-black) - free product
- [Django Material Dashboard](https://appseed.us/admin-dashboards/django-dashboard-material) - free product
- [Datta Able PRO](https://jinja-datta-able-pro.appseed.us/layout-rtl.html) - commercial product
- [Material PRO](https://theme-jinja2-material-dashboard-pro.appseed.us/page-rtl.html) - commercial product

Let us know if you need further assistance.
